# Shrey Viradiya
### 18BCE259

# Naive Bayes Classifiers


In [1]:
import numpy as np
import pandas as pd
from sklearn.naive_bayes import GaussianNB, BernoulliNB, MultinomialNB
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.metrics import *
import plotly.graph_objects as go
import plotly.express as px
from collections import Counter

In [2]:
np.random.seed(259)

## Data

In [3]:
iris = load_iris()

In [4]:
print("IRIS Dataset")
print(f"Feature names: {iris['feature_names']}")
print(f"Target names: {iris['target_names']}")

IRIS Dataset
Feature names: [&#39;sepal length (cm)&#39;, &#39;sepal width (cm)&#39;, &#39;petal length (cm)&#39;, &#39;petal width (cm)&#39;]
Target names: [&#39;setosa&#39; &#39;versicolor&#39; &#39;virginica&#39;]


In [5]:
X = iris['data']
y = iris['target']
X = pd.DataFrame(X, columns=iris['feature_names'])

In [6]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.5, random_state=259)

## GaussianNB Naive Bayes

In [7]:
gauss = GaussianNB()
gauss.fit(X_train, y_train)

GaussianNB()

In [8]:
prediction = gauss.predict(X_test)

In [9]:
print("Report: ____________________________\n")
print(f"Accuracy: {accuracy_score(y_test, prediction)}")
print("Confisuion metrix:")
print(confusion_matrix(y_test, prediction))
print("Classification Report:")
print(classification_report(y_test, prediction))

Report: ____________________________

Accuracy: 0.9333333333333333
Confisuion metrix:
[[28  0  0]
 [ 0 18  3]
 [ 0  2 24]]
Classification Report:
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        28
           1       0.90      0.86      0.88        21
           2       0.89      0.92      0.91        26

    accuracy                           0.93        75
   macro avg       0.93      0.93      0.93        75
weighted avg       0.93      0.93      0.93        75



### GaussianNB without sklearn

In [8]:
class GNB:
    def __init__(self):
        self.means = None
        self.stds = None
        self.class_prab = None
        self.classes = None
    
    def fit(self,X_train, y_train):
        self.means = X_train.groupby(y_train).apply(np.mean)
        print(self.means)
        self.stds = X_train.groupby(y_train).apply(np.std)
        print(self.stds)
        self.class_prob = X_train.groupby(y_train).apply(lambda x: len(x)/X_train.shape[0])
        self.classes = np.unique(y_train)
    
    def predict(self,X_test):
        y_pred = []
        for index in range(X_test.shape[0]):
            p = {}
            for clss in self.classes:
                p[clss] = self.class_prob[clss]
                for idx, value in enumerate(X_test.iloc[index]):
                    p[clss] *= ( 1/(np.sqrt(2 * np.pi)*self.stds.iloc[clss, idx]) )* np.exp( -(value - self.means.iloc[clss, idx])**2/(2* (self.stds.iloc[clss, idx])**2 ))
            y_pred.append(pd.Series(p).values.argmax())
        return y_pred

In [9]:
X_train = np.array([[95,75,85],
    [80,89,85],
    [64,70,60],
    [83,78,70],
    [73,99,93],
    [68,73,80],
    [64,65,70]
])

X_train = pd.DataFrame(X_train)
y_train = np.array([0,0,0,1,1,1,1])


X_test = np.array([[90,80,85]])
X_test = pd.DataFrame(X_test)

gnb = GNB()
gnb.fit(X_train, y_train)
prediction = gnb.predict(X_test)

           0      1          2
0  79.666667  78.00  76.666667
1  72.000000  78.75  78.250000
           0          1          2
0  12.657892   8.041559  11.785113
1   7.106335  12.577261   9.443913


In [7]:
prediction

[0]

In [6]:
print("Report: ____________________________\n")
print(f"Accuracy: {accuracy_score(y_test, prediction)}")
print("Confisuion metrix:")
print(confusion_matrix(y_test, prediction))
print("Classification Report:")
print(classification_report(y_test, prediction))

Report: ____________________________



NameError: name 'y_test' is not defined

## Text Data

In [13]:
amazon = pd.read_csv('amazon_cells_labelled.txt',delimiter='\t')
imdb = pd.read_csv('imdb_labelled.txt',delimiter='\t')
yelp = pd.read_csv('yelp_labelled.txt',delimiter='\t')
reviews = pd.concat([amazon, imdb, yelp])
# reviews = yelp

In [14]:
reviews

Sentence  bool
0    So there is no way for me to plug it in here i...     0
1                          Good case, Excellent value.     1
2                               Great for the jawbone.     1
3    Tied to charger for conversations lasting more...     0
4                                    The mic is great.     1
..                                                 ...   ...
995  I think food should have flavor and texture an...     0
996                           Appetite instantly gone.     0
997  Overall I was not impressed and would not go b...     0
998  The whole experience was underwhelming, and I ...     0
999  Then, as if I hadn&#39;t wasted enough of my life ...     0

[2748 rows x 2 columns]

## Multivariate Bernoulli Naive Bayes

In [15]:
vectorizer = CountVectorizer(stop_words = 'english', binary = True)
X = vectorizer.fit_transform(reviews['Sentence'])
X = np.array(X.toarray())
y = np.array(reviews['bool'])
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=259)

In [16]:
Bern = BernoulliNB()

In [17]:
Bern.fit(X_train, y_train)

BernoulliNB()

In [18]:
prediction = Bern.predict(X_test)

In [19]:
print("Report: ____________________________\n")
print(f"Accuracy: {accuracy_score(y_test, prediction)}")
print("Confisuion metrix:")
print(confusion_matrix(y_test, prediction))
print("Classification Report:")
print(classification_report(y_test, prediction))

Report: ____________________________

Accuracy: 0.7945454545454546
Confisuion metrix:
[[198  72]
 [ 41 239]]
Classification Report:
              precision    recall  f1-score   support

           0       0.83      0.73      0.78       270
           1       0.77      0.85      0.81       280

    accuracy                           0.79       550
   macro avg       0.80      0.79      0.79       550
weighted avg       0.80      0.79      0.79       550



## Multinomial Naive Bayes

In [20]:
vectorizer = CountVectorizer(stop_words = 'english')
X = vectorizer.fit_transform(reviews['Sentence'])
X = np.array(X.toarray())
y = np.array(reviews['bool'])
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=259)

In [21]:
Mnom = MultinomialNB()

In [22]:
Mnom.fit(X_train, y_train)

MultinomialNB()

In [23]:
prediction = Mnom.predict(X_test)

In [24]:
print("Report: ____________________________\n")
print(f"Accuracy: {accuracy_score(y_test, prediction)}")
print("Confisuion metrix:")
print(confusion_matrix(y_test, prediction))
print("Classification Report:")
print(classification_report(y_test, prediction))

Report: ____________________________

Accuracy: 0.7909090909090909
Confisuion metrix:
[[202  68]
 [ 47 233]]
Classification Report:
              precision    recall  f1-score   support

           0       0.81      0.75      0.78       270
           1       0.77      0.83      0.80       280

    accuracy                           0.79       550
   macro avg       0.79      0.79      0.79       550
weighted avg       0.79      0.79      0.79       550

