# Shrey Viradiya
### 18BCE259

## Support Vector Machines

In [1]:
import numpy as np
from sklearn import datasets
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.svm import LinearSVC, SVC
from sklearn import metrics
from sklearn.model_selection import train_test_split

np.random.seed(259)

In [2]:
def Report(clf, prediction, y_true, class_names):
    print("Prediction Report: ", clf.__name__)
    print("===================")

    print("Accuracy: ", metrics.accuracy_score(y_true, prediction))
    print(metrics.classification_report(y_true, prediction, target_names = class_names))
    print(metrics.confusion_matrix(y_true, prediction))

## Linear Support Vector Classifier

### Data

In [3]:
iris = datasets.load_iris()
class_names, feature_names = iris['target_names'], iris['feature_names']
X = iris['data']
y = iris['target']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.5, random_state=259)

### Classifier

In [4]:
svm_clf = Pipeline([
                    ('scaler', StandardScaler()),
                    ('linear_svc', LinearSVC(C = 1, loss='hinge'))
])
svm_clf.__name__ = "LinearSVC"

In [5]:
svm_clf.fit(X_train,y_train)

Pipeline(steps=[('scaler', StandardScaler()),
                ('linear_svc', LinearSVC(C=1, loss='hinge'))])

In [6]:
prediction_svm_clf = svm_clf.predict(X_test)

In [7]:
Report(svm_clf, prediction_svm_clf, y_test, class_names)

Prediction Report:  LinearSVC
Accuracy:  0.92
              precision    recall  f1-score   support

      setosa       1.00      1.00      1.00        28
  versicolor       0.86      0.86      0.86        21
   virginica       0.88      0.88      0.88        26

    accuracy                           0.92        75
   macro avg       0.91      0.91      0.91        75
weighted avg       0.92      0.92      0.92        75

[[28  0  0]
 [ 0 18  3]
 [ 0  3 23]]


## Nonlinear SVM Classification

### Data

In [8]:
X,y = datasets.make_moons(n_samples = 100, noise = 0.15)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state=259)

### Classifier

In [9]:
poly_kernel_svm_clf = Pipeline([
                                 ('scaler', StandardScaler()),
                                 ('svm_clf', SVC(kernel='poly', degree = 3, coef0=1, C =5))
])
poly_kernel_svm_clf.__name__ = "SVC_poly"

In [10]:
poly_kernel_svm_clf.fit(X_train,y_train)

Pipeline(steps=[('scaler', StandardScaler()),
                ('svm_clf', SVC(C=5, coef0=1, kernel='poly'))])

In [11]:
prediction_poly_svm_clf = poly_kernel_svm_clf.predict(X_test)

In [12]:
Report(poly_kernel_svm_clf, prediction_poly_svm_clf, y_test, None)

Prediction Report:  SVC_poly
Accuracy:  0.96
              precision    recall  f1-score   support

           0       0.92      1.00      0.96        12
           1       1.00      0.92      0.96        13

    accuracy                           0.96        25
   macro avg       0.96      0.96      0.96        25
weighted avg       0.96      0.96      0.96        25

[[12  0]
 [ 1 12]]
