# Shrey Viradiya
### 18BCE259

# Grid Search

In [1]:
import numpy as np
import pandas as pd
from sklearn.neighbors import KNeighborsClassifier
from sklearn.datasets import load_iris, load_boston
from sklearn.model_selection import GridSearchCV, train_test_split
from sklearn.linear_model import SGDRegressor
from sklearn.metrics import *
from sklearn.utils import shuffle
from sklearn.preprocessing import StandardScaler

np.random.seed(259)

## Classifier

In [2]:
iris = load_iris()

In [3]:
print("IRIS Dataset")
print(f"Feature names: {iris['feature_names']}")
print(f"Target names: {iris['target_names']}")

IRIS Dataset
Feature names: ['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']
Target names: ['setosa' 'versicolor' 'virginica']


In [4]:
X = iris['data']
y = iris['target']

In [5]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.5, random_state=259)

In [6]:
neigh = KNeighborsClassifier()

In [7]:
KNeighborsClassifier?

Init signature:
KNeighborsClassifier(
    n_neighbors=5,
    *,
    weights='uniform',
    algorithm='auto',
    leaf_size=30,
    p=2,
    metric='minkowski',
    metric_params=None,
    n_jobs=None,
    **kwargs,
)
Docstring:     
Classifier implementing the k-nearest neighbors vote.

Read more in the :ref:`User Guide <classification>`.

Parameters
----------
n_neighbors : int, default=5
    Number of neighbors to use by default for :meth:`kneighbors` queries.

weights : {'uniform', 'distance'} or callable, default='uniform'
    weight function used in prediction.  Possible values:

    - 'uniform' : uniform weights.  All points in each neighborhood
      are weighted equally.
    - 'distance' : weight points by the inverse of their distance.
      in this case, closer neighbors of a query point will have a
      greater influence than neighbors which are further away.
    - [callable] : a user-defined function which accepts an
      array of distances, and returns an array of the sa

### Grid Search Dictionary and Object

In [8]:
param_grid = {
    'n_neighbors' : [1,5,10,20],
    'weights' : ['uniform', 'distance']
}

clf_grid = GridSearchCV(neigh, param_grid, cv = 5)
clf_grid.fit(X_train, y_train)

GridSearchCV(cv=5, estimator=KNeighborsClassifier(),
             param_grid={'n_neighbors': [1, 5, 10, 20],
                         'weights': ['uniform', 'distance']})

In [9]:
print(f"Best Parameters: {clf_grid.best_params_}")

Best Parameters: {'n_neighbors': 10, 'weights': 'distance'}


In [10]:
prediction = clf_grid.predict(X_test)

In [11]:
print("Report: ____________________________\n")
print(f"Accuracy: {accuracy_score(y_test, prediction)}")
print("Confisuion metrix:")
print(confusion_matrix(y_test, prediction))
print("Classification Report:")
print(classification_report(y_test, prediction))

Report: ____________________________

Accuracy: 0.96
Confisuion metrix:
[[28  0  0]
 [ 0 19  2]
 [ 0  1 25]]
Classification Report:
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        28
           1       0.95      0.90      0.93        21
           2       0.93      0.96      0.94        26

    accuracy                           0.96        75
   macro avg       0.96      0.96      0.96        75
weighted avg       0.96      0.96      0.96        75



## Regressor

In [12]:
X, y = load_boston(return_X_y=True)
X, y = shuffle(X, y, random_state = 259)
X = StandardScaler().fit_transform(X)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20, random_state=259)

In [13]:
sgd_clf = SGDRegressor()

In [14]:
SGDRegressor?

Init signature:
SGDRegressor(
    loss='squared_loss',
    *,
    penalty='l2',
    alpha=0.0001,
    l1_ratio=0.15,
    fit_intercept=True,
    max_iter=1000,
    tol=0.001,
    shuffle=True,
    verbose=0,
    epsilon=0.1,
    random_state=None,
    learning_rate='invscaling',
    eta0=0.01,
    power_t=0.25,
    early_stopping=False,
    validation_fraction=0.1,
    n_iter_no_change=5,
    warm_start=False,
    average=False,
)
Docstring:     
Linear model fitted by minimizing a regularized empirical loss with SGD

SGD stands for Stochastic Gradient Descent: the gradient of the loss is
estimated each sample at a time and the model is updated along the way with
a decreasing strength schedule (aka learning rate).

The regularizer is a penalty added to the loss function that shrinks model
parameters towards the zero vector using either the squared euclidean norm
L2 or the absolute norm L1 or a combination of both (Elastic Net). If the
parameter update crosses the 0.0 value because of t

### Grid Search Dictionary and Object

In [15]:
param_grid = {
    'eta0' : [0.1, 0.05, 0.01, 0.0050, 0.001],
    'power_t' : [0.1, 0.5, 0.25],
    'penalty' : ['l2', 'l1', 'elasticnet'],
    'early_stopping' : [False, True],
    'max_iter' : [500, 1000, 1500, 2000],
    'learning_rate' : ['constant', 'optimal', 'invscaling', 'adaptive']
}

clf_grid = GridSearchCV(sgd_clf, param_grid, cv = 5)
clf_grid.fit(X_train, y_train)

GridSearchCV(cv=5, estimator=SGDRegressor(),
             param_grid={'early_stopping': [False, True],
                         'eta0': [0.1, 0.05, 0.01, 0.005, 0.001],
                         'learning_rate': ['constant', 'optimal', 'invscaling',
                                           'adaptive'],
                         'max_iter': [500, 1000, 1500, 2000],
                         'penalty': ['l2', 'l1', 'elasticnet'],
                         'power_t': [0.1, 0.5, 0.25]})

In [16]:
print(f"Best Parameters: {clf_grid.best_params_}")

Best Parameters: {'early_stopping': True, 'eta0': 0.05, 'learning_rate': 'adaptive', 'max_iter': 1000, 'penalty': 'elasticnet', 'power_t': 0.25}


In [17]:
prediction = clf_grid.predict(X_test)

In [18]:
print("Report: ____________________________\n")
print(f"Accuracy: MAE {mean_absolute_error (y_true= y_test, y_pred= prediction)}")
print(f"Accuracy: MSE {mean_squared_error (y_true= y_test, y_pred= prediction)}")

Report: ____________________________

Accuracy: MAE 3.8040372056478025
Accuracy: MSE 27.873075672679253
